site_name: 'Funciona con .yml'
repo_url: https://github.com/JParisR/BikeRental/

nav:
  - Home: index.md
  - Home: information.md

plugins:
  - techdocs-core
  - search
      theme:
        features:
          - search.highlight
          - search.suggest
