site_name: 'Funciona con .yml'
repo_url: https://github.com/JParisR/BikeRental/

markdown_extensions:
  - admonition
  
plugins:
  - techdocs-core
  - search:
      themes:
        features:
          - search.highlight
          - search.suggest
nav:
  - Home: index.md
  - Home: information.md


